linters:
  disable-all: true
  enable:
    # https://golangci-lint.run/usage/linters/#enabled-by-default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # https://golangci-lint.run/usage/linters/#disabled-by-default
    - gofmt
    - asasalint
    - asciicheck
    - contextcheck
    - copyloopvar
    - cyclop
    - dogsled
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - fatcontext
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocognit
    - gocritic
    - gocyclo
    - gosec
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - makezero
    - mirror
    - musttag
    - nestif
    - nilnil
    - paralleltest
    - prealloc
    - predeclared
    - reassign
    - thelper
    - tparallel
    - unconvert
    - usestdlibvars
    - wastedassign
    - whitespace
