services:
  db:
    image: "postgres:16.3-bookworm"
    environment:
      POSTGRES_USER: entdemo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: entdemo
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "entdemo", "-U", "entdemo" ]
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 5
    ports:
      - "5432:5432"
    expose:
      - "5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: entdemo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: entdemo
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - path: ./
          action: sync+restart
          target: /src
          ignore: [ "main", "entdemo" ]
    ports:
      - "1323:1323"
